version: '2.1'
services:
    rugbyapi:
        build: .
        ports:
            - "8080:8080"
        environment:
            DATABASE_URL: "sqlite:///./sql_app.db"

    db:
        image: postgres:13.1
        restart: always
        environment:
            POSTGRES_PASSWORD: password